### ISSUE TITLE
WriteString does not output anything to stdout

### ISSUE THREAD

**Issue by vsht** [WolframResearch/WolframLanguageForJupyter#77]
The following 
```
WriteString["stdout","Hello world!"]
```
produces no output contrary to the normal behavior of the front end.

**Comment by cc-wr** [comment]
I have created a pull request for a solution to this issue at #79.

However, I will note that #79 is somewhat of a half-measure: rather than replacing the original stdout stream with a stream that writes to Jupyter, #79 replaces string references to the stdout stream in `WriteString` and `Write` (like `"stdout"` in `WriteString["stdout","Hello world!"]`) with a stream that writes to Jupyter.

It may be possible in the future for this project to be able to close the original stdout stream and replace it with a stream that writes to Jupyter, but to me, this does not seem possible now.

**Comment by vsht** [comment]
Everything seems to work as expected with #79. I tested both the output to stdout and to a file.
Thanks for the quick fix!

**Comment by cc-wr** [comment]
A general request for comments on the pull request for addressing this issue, #79, is at #80.

**Comment by cc-wr** [comment]
This issue should be resolved in `master`.
