### ISSUE TITLE
Wolfram Language 12.1 kernel dies running  WolframModel

### ISSUE THREAD

**Issue by s1a2t3y4** [WolframResearch/WolframLanguageForJupyter#87]
kernel dies when i run
ResourceFunction["WolframModel"][{{1, 2, 3}, {2, 4, 5}} ->
  {{5, 6, 1}, {6, 4, 2}, {4, 5, 3}},
 {{1, 2, 3}, {2, 4, 5}, {4, 6, 7}}, 1]

![image](https://user-images.githubusercontent.com/5167739/82815457-3ec2df00-9e67-11ea-8b0a-d09800a3dbb6.png)

**Comment by cc-wr** [comment]
I am working to reproduce this issue.

**Comment by JamesMcDean** [comment]
I am suffering from the same issue on all attempts of model generation using Ubuntu 20.04. Things like Plot3D are working fine though.

**Comment by drzraf** [comment]
Same problem (seeing some `munmap_chunk(): invalid pointer` in the logs)

**Comment by cc-wr** [comment]
@s1a2t3y4, @JamesMcDean, @drzraf,

(I apologize for the delay.)

I can reproduce this issue (only) on Linux.

This issue seems to result from a bad interaction between the SetReplace paclet, which defines `WolframModel`, and the paclet MXNetLink, which `WolframLanguageForJupyter` accidentally makes use of.

You should be able to verify this by running (outside of `WolframLanguageForJupyter`) the following code, which should crash kernel:

```
In[1]:= Needs["MXNetLink`"]                                                     
                                                                                
In[2]:= Needs["SetReplace`"]                                                    

In[3]:= (* WARNING: This will crash the kernel. *) WolframModel[{{1, 2, 3}, {2, 4, 5}} -> {{5, 6, 1}, {6, 4, 2}, {4, 5, 3}}, {{1, 2, 3}, {2, 4, 5}, {4, 6, 7}}, 1]
```

---

We will look further into why this bad interaction occurs, but for the moment, we can just stop `WolframLanguageForJupyter` from accidentally loading `MXNetLink` with the pull request #92. Let me know if #92 resolves the immediate issue for you.

**Comment by cc-wr** [comment]
> We will look further into why this bad interaction occurs, but for the moment, we can just stop WolframLanguageForJupyter from accidentally loading MXNetLink with the pull request #92. Let me know if #92 resolves the immediate issue for you.

A general request for comments on the pull request #92 is at #101.

**Comment by cc-wr** [comment]
Additionally, I can no longer reproduce the bad interaction between `MXNetLink` and `SetReplace`. Presumably (at least) one of them has been paclet updated in such a way as to resolve the issue.
